environment: production
# Comma separated list of Ethereum archive node URLs
eth_rpc_urls: <eth_rpc_urls>
# Aethos ServiceManager Proxy Contract
service_manager_contract: 0xdE93E0dA148e1919bb7f33cd8847F96e45791210
## Eigenlayer AVS Directory Contract (Holesky)
eigen_avs_directory_contract: 0x055733000064333CaDDbC92763c58BF0192fFeBf
# Registration private key store path
registration_private_key_store_path: <path_to_private_key_store>
# Password to access the private key store
registration_private_key_password: <password>
# Aethos signing private key store path
aethos_signing_private_key_store_path: <path_to_private_key_store>
# Password to access the signing private key store
aethos_signing_private_key_password: <password>
# GRPC server on which the operator listens for messages from the middleware
public_task_server_endpoint: <your_public_ip_address>:9010
# Internal GRPC server the public server forwards messages to
internal_task_server_endpoint: 0.0.0.0:9010
# Middleware DNS and port
middleware_server_endpoint: holesky.task.aethos.network:50051
# Encompasses operator metrics including eigen metrics
metrics_server_endpoint: 0.0.0.0:9090
# Eigen avs node spec compliance https://eigen.nethermind.io/docs/spec/intro
eigen_avs_node_api_server_endpoint: 0.0.0.0:8080
# db path
db_path: /app/data/
# enable log colors
enable_log_color: true