environment: production
# Predicate ServiceManager Proxy Contract
service_manager_contract: 0xc75F360e4F801F61975a425c405f1472c550ef55
## Eigenlayer AVS Directory Contract (Holesky)
eigen_avs_directory_contract: 0x055733000064333CaDDbC92763c58BF0192fFeBf
# Internal GRPC server the public server forwards messages to
internal_task_server_endpoint: 0.0.0.0:9010
# Middleware DNS and port
middleware_server_endpoint: testnet.task.predicate.io:50051
# Encompasses operator metrics including eigen metrics
metrics_server_endpoint: 0.0.0.0:9090
# Eigen avs node spec compliance https://eigen.nethermind.io/docs/spec/intro
eigen_avs_node_api_server_endpoint: 0.0.0.0:8080
# db path
db_path: /app/data/
# enable log colors
enable_log_color: true

###############################################################################
####### TODO: Operators please update below values for your node ##############
###############################################################################

# GRPC server on which the operator listens for messages from the middleware
public_task_server_endpoint: <your_public_ip_address>:9010
# Registration private key store path
registration_private_key_store_path: <path_to_private_key_store>
# Password to access the private key store
registration_private_key_password: <password>
# Predicate signing private key store path
predicate_signing_private_key_store_path: <path_to_private_key_store>
# Password to access the signing private key store
predicate_signing_private_key_password: <password>
# Comma separated list of Holesky RPC URLs e.g. [https://holesky.abc.io/v3/your-api-key, https://holesky.def.io/v3/your-api-key]
eth_rpc_urls: []
